### PR TITLE
add tune option to gen target boards

### PR DESCRIPTION
**Pull request by ewlu**
`--with-tune` actually sets target board tune

### CODE REVIEW

**Comment by patrick-rivos** [comment]
Currently testing locally

**Comment by patrick-rivos** [comment]
Tested locally - Running with --tune=rocket is the same as not providing it and --tune=thead shows a change in the number of fails. Thanks!

**Review by patrick-rivos — APPROVED** [review]

**Comment by patrick-rivos** [comment]
This change looks generic too - would be good to upstream it

**Comment by ewlu** [comment]
Upstream has their own version of testing target boards https://github.com/riscv-collab/riscv-gnu-toolchain/blob/master/Makefile.in#L100

**Pull request merged**
